<?php
return [
  'civicfg_sync_dir' => [
    'group_name' => 'Configuration Manager',
    'group' => 'configuration_manager',
    'name' => 'civicfg_sync_dir',
    'type' => 'String',
    'html_type' => 'Text',
    'default' => 'civicrm-config',
    'add' => '5.0',
    'title' => ts('Configuration Manager Sync Directory'),
    'description' => ts('Directory used for CiviCRM configuration YAML files.'),
    'is_domain' => 1,
    'is_contact' => 0,
  ],
  'civicfg_enabled_types' => [
    'group_name' => 'Configuration Manager',
    'group' => 'configuration_manager',
    'name' => 'civicfg_enabled_types',
    'type' => 'Array',
    'html_type' => 'Text',
    'default' => [],
    'add' => '5.0',
    'title' => ts('Configuration Manager Enabled Types'),
    'description' => ts('Enabled configuration type keys. Empty means all supported phase 1 types.'),
    'is_domain' => 1,
    'is_contact' => 0,
  ],
  'civicfg_ignore_paths' => [
    'group_name' => 'Configuration Manager',
    'group' => 'configuration_manager',
    'name' => 'civicfg_ignore_paths',
    'type' => 'Array',
    'html_type' => 'Text',
    'default' => [],
    'add' => '5.0',
    'title' => ts('Configuration Manager Ignored YAML Paths'),
    'description' => ts('Relative YAML paths or wildcard patterns ignored by Configuration Manager.'),
    'is_domain' => 1,
    'is_contact' => 0,
  ],
  'civicfg_settings_allowlist' => [
    'group_name' => 'Configuration Manager',
    'group' => 'configuration_manager',
    'name' => 'civicfg_settings_allowlist',
    'type' => 'Array',
    'html_type' => 'Text',
    'default' => [
      'defaultCurrency',
      'dateformatDatetime',
      'dateformatFull',
      'dateformatPartial',
      'dateformatYear',
      'fiscalYearStart',
      'lcMessages',
      'lcMonetary',
      'mailing_backend',
      'maxFileSize',
      'theme_backend',
      'theme_frontend',
    ],
    'add' => '5.0',
    'title' => ts('Configuration Manager Settings Allowlist'),
    'description' => ts('CiviCRM setting names that are allowed to be exported.'),
    'is_domain' => 1,
    'is_contact' => 0,
  ],
];
