<?php
return [
  'civicfg_sync_dir' => [
    'group_name' => 'Configuration Manager',
    'group' => 'configuration_manager',
    'name' => 'civicfg_sync_dir',
    'type' => 'String',
    'html_type' => 'Text',
    'default' => 'civicrm-config',
    'add' => '5.0',
    'title' => ts('Configuration Manager Sync Directory'),
    'description' => ts('Directory used for CiviCRM configuration YAML files.'),
    'is_domain' => 1,
    'is_contact' => 0,
  ],

  'civicfg_site_id' => [
    'group_name' => 'Configuration Manager',
    'group' => 'configuration_manager',
    'name' => 'civicfg_site_id',
    'type' => 'String',
    'html_type' => 'Text',
    'default' => '',
    'add' => '5.0',
    'title' => ts('Configuration Manager Site Identifier'),
    'description' => ts('Automatically generated shared identifier for one site family across environments. Import validation blocks YAML from another site unless experimental cross-site import is enabled.'),
    'is_domain' => 1,
    'is_contact' => 0,
  ],
  'civicfg_allow_cross_site_import' => [
    'group_name' => 'Configuration Manager',
    'group' => 'configuration_manager',
    'name' => 'civicfg_allow_cross_site_import',
    'type' => 'Boolean',
    'html_type' => 'Checkbox',
    'default' => 0,
    'add' => '5.0',
    'title' => ts('Configuration Manager Allow Cross-site Import'),
    'description' => ts('Experimental. Allow importing YAML when the manifest site identifier differs from this site. Keep disabled for normal dev/stage/prod synchronization.'),
    'is_domain' => 1,
    'is_contact' => 0,
  ],
  'civicfg_ignore_values' => [
    'group_name' => 'Configuration Manager',
    'group' => 'configuration_manager',
    'name' => 'civicfg_ignore_values',
    'type' => 'Array',
    'html_type' => 'Text',
    'default' => [],
    'add' => '5.0',
    'title' => ts('Configuration Manager Ignored YAML Values'),
    'description' => ts('Relative YAML path plus dot-path rules ignored during diff, export, import, and single-file preview.'),
    'is_domain' => 1,
    'is_contact' => 0,
  ],
  'civicfg_enabled_types' => [
    'group_name' => 'Configuration Manager',
    'group' => 'configuration_manager',
    'name' => 'civicfg_enabled_types',
    'type' => 'Array',
    'html_type' => 'Text',
    'default' => [],
    'add' => '5.0',
    'title' => ts('Configuration Manager Enabled Types'),
    'description' => ts('Enabled configuration type keys. Empty means all supported phase 1 types.'),
    'is_domain' => 1,
    'is_contact' => 0,
  ],
  'civicfg_ignore_paths' => [
    'group_name' => 'Configuration Manager',
    'group' => 'configuration_manager',
    'name' => 'civicfg_ignore_paths',
    'type' => 'Array',
    'html_type' => 'Text',
    'default' => [],
    'add' => '5.0',
    'title' => ts('Configuration Manager Ignored YAML Paths'),
    'description' => ts('Relative YAML paths or wildcard patterns ignored by Configuration Manager.'),
    'is_domain' => 1,
    'is_contact' => 0,
  ],
  'civicfg_settings_allowlist' => [
    'group_name' => 'Configuration Manager',
    'group' => 'configuration_manager',
    'name' => 'civicfg_settings_allowlist',
    'type' => 'Array',
    'html_type' => 'Text',
    'default' => [
      'defaultCurrency',
      'dateformatDatetime',
      'dateformatFull',
      'dateformatPartial',
      'dateformatYear',
      'fiscalYearStart',
      'lcMessages',
      'lcMonetary',
      'mailing_backend',
      'maxFileSize',
      'theme_backend',
      'theme_frontend',
    ],
    'add' => '5.0',
    'title' => ts('Configuration Manager Settings Allowlist'),
    'description' => ts('CiviCRM setting names that are allowed to be exported.'),
    'is_domain' => 1,
    'is_contact' => 0,
  ],
];
