<?php
namespace Civi\ConfigManager\Util;

/**
 * Small YAML helper.
 * Uses Symfony YAML when available; otherwise writes a readable YAML subset.
 * Avoid yaml_emit() for exports because ext-yaml renders null as '~', which is less clear for config review.
 * The fallback parser is intentionally limited; reading prefers Symfony YAML or ext-yaml.
 */
class SimpleYaml {
  public static function dump(array $data): string {
    if (class_exists('Symfony\\Component\\Yaml\\Yaml')) {
      return self::normaliseYamlOutput(\Symfony\Component\Yaml\Yaml::dump($data, 8, 2));
    }
    return self::normaliseYamlOutput(self::dumpValue($data, 0) . "\n");
  }

  /**
   * Normalise YAML generated by different libraries so exported files stay
   * easier to read and do not switch between `~` and `null` for empty values.
   */
  private static function normaliseYamlOutput(string $yaml): string {
    $yaml = preg_replace('/^---\s*\R/', '', $yaml);
    $yaml = preg_replace('/\R\.\.\.\s*$/', "\n", $yaml);
    $yaml = preg_replace('/(:\s*)~(\s*(?:#.*)?$)/m', '$1null$2', $yaml);
    $yaml = preg_replace('/(^\s*-\s*)~(\s*(?:#.*)?$)/m', '$1null$2', $yaml);
    return rtrim($yaml) . "\n";
  }

  public static function parseFile(string $file): array {
    if (class_exists('Symfony\\Component\\Yaml\\Yaml')) {
      $data = \Symfony\Component\Yaml\Yaml::parseFile($file);
      return is_array($data) ? $data : [];
    }
    if (function_exists('yaml_parse_file')) {
      $data = yaml_parse_file($file);
      return is_array($data) ? $data : [];
    }
    // Fallback: retain raw file for diff/status. Import should require a real YAML parser.
    return ['__raw_yaml' => file_get_contents($file)];
  }

  private static function dumpValue($value, int $indent): string {
    if (is_array($value)) {
      return self::dumpArray($value, $indent);
    }
    return self::scalar($value);
  }

  private static function dumpArray(array $array, int $indent): string {
    $lines = [];
    $isList = array_keys($array) === range(0, count($array) - 1);
    foreach ($array as $key => $value) {
      $pad = str_repeat(' ', $indent);
      if ($isList) {
        if (is_array($value)) {
          $lines[] = $pad . '-';
          $lines[] = self::dumpValue($value, $indent + 2);
        }
        else {
          $lines[] = $pad . '- ' . self::scalar($value);
        }
      }
      else {
        if (is_array($value)) {
          $lines[] = $pad . self::key($key) . ':';
          $lines[] = self::dumpValue($value, $indent + 2);
        }
        else {
          $lines[] = $pad . self::key($key) . ': ' . self::scalar($value);
        }
      }
    }
    return implode("\n", $lines);
  }

  private static function key($key): string {
    return preg_match('/^[A-Za-z0-9_.-]+$/', (string) $key) ? (string) $key : self::scalar((string) $key);
  }

  private static function scalar($value): string {
    if ($value === NULL) {
      return 'null';
    }
    if ($value === TRUE) {
      return 'true';
    }
    if ($value === FALSE) {
      return 'false';
    }
    if (is_int($value) || is_float($value)) {
      return (string) $value;
    }
    $value = (string) $value;
    if ($value === '') {
      return "''";
    }
    if (strpos($value, "\n") !== FALSE) {
      $lines = explode("\n", $value);
      return "|\n    " . implode("\n    ", $lines);
    }
    return json_encode($value, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
  }
}
